### ISSUE TITLE
Misc. visual enhancements for extension

### ISSUE THREAD

**Issue by rvanbekkum** [StefanMaron/vsc-lintercop#2]
Here are some suggestions for enhancements for the VSCode extension:
* The screenshots are not shown when you view the extension in the Visual Studio Marketplace or Visual Studio Code:
   
   ![image](https://user-images.githubusercontent.com/7383241/143579967-65509efb-4d88-48bf-84c1-c9cc876fadf3.png)

* The extension cannot be found that easily with the search function in VSCode. Maybe you can add some search keywords?
* The CHANGELOG is empty.
* The extension does not have a logo yet.
* The Repository link points to the GitHub repository of the code analyzer instead of the vsc-lintercop GitHub repository. It might be nice to change this and add a link in the README to point to the code analyzer repo.
* Might be nice to add badges to the README to indicate the installs and the LICENSE that applies. 😄
* Add the license property to the extension's `package.json`

**Comment by StefanMaron** [comment]
Keywords were already added, but it seems they just dont work.

The rest I tried to address :)
