### ISSUE TITLE
LC0005 doesn't work in XmlPost

### ISSUE THREAD

**Issue by guidorobben** [StefanMaron/vsc-lintercop#20]
LC0005 doesn't check the fieldelement in an XmlPort.

tableelement(Item; Item)

![image](https://github.com/StefanMaron/vsc-lintercop/assets/11609736/6c20953c-4d92-4eb5-8f0b-4d19d447ee36)

I would expect an warning for the two item lines (200, 212)

**Comment by Arthurvdv** [comment]
This repo is only for the VS Code extension to download the LinterCop.

I can't move an issue between the repositories unfortunately. Please close this issue here and create a new one here: https://github.com/StefanMaron/BusinessCentral.LinterCop

**Comment by guidorobben** [comment]
Will do
