### ISSUE TITLE
Check the linter warnings in the Pull Request

### ISSUE THREAD

**Issue by Lazys** [StefanMaron/vsc-lintercop#3]
We're using Azure Dev Ops and Pull Requests. Do you have any idea how could we add your linter to the Pull Request as the "gate" or sth like this?

In another words - how can we check on the Pull Request if there are no warnings in the code that someone wants to merge to the main branch?

I'm looking for sth similar as SonarQube - https://www.sonarqube.org/microsoft-azure-devops-integration/

**Comment by StefanMaron** [comment]
I am not using azure devops, but I know that the Run-ALPipeline command has a parameter -failOnWarning.

https://www.powershellgallery.com/packages/BcContainerHelper/3.0.0/Content/AppHandling%5CRun-AlPipeline.ps1

![image](https://user-images.githubusercontent.com/24838311/147457976-73eb1a84-e9ba-4c3d-b6b2-8652cefacf84.png)

You can also pass in custom cops like this linter:

![image](https://user-images.githubusercontent.com/24838311/147458029-bdbc1204-269c-4a89-b571-353c89938b6b.png)

**Comment by Lazys** [comment]
Thanks for the idea.
