### ISSUE TITLE
LC throws 207,000 lines of warnings after update to AL Language v11

### ISSUE THREAD

**Issue by NKarolak** [StefanMaron/vsc-lintercop#9]
Since I updated to AL Language v11, the Linter cop is over-active whenever I create a package: 207,000 output lines.
A block of permission lines is repeated over and over again.
I'd like to share the full output file with you, but not publicly.

**Comment by jwikman** [comment]
According to Stefan, a new version of the dll is released: https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/280

**Comment by StefanMaron** [comment]
Yep, was just about to comment here as well, thanks @jwikman

**Comment by NKarolak** [comment]
Ah cool, let me quickly check ...
Btw, this influence of the linter cop was weird:
https://github.com/microsoft/AL/issues/7356#issuecomment-1494419590
